#!/usr/bin/env python3
"""
Render config.yaml -> nanobot/nanobot.config.json and .env for docker-compose.

Runs from setup.sh. Keeps the whole system driven by a single yaml file.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

try:
    import yaml  # PyYAML
except ImportError:
    sys.stderr.write(
        "ERROR: PyYAML not installed. Run: pip install pyyaml\n"
    )
    sys.exit(1)


ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config.yaml"
NANOBOT_OUT = ROOT / "nanobot" / "nanobot.config.json"
ENV_OUT = ROOT / ".env"
PROMPTS_DIR = ROOT / "prompts"


PLACEHOLDER_RE = re.compile(r"\{\{[^}]+\}\}")


def die(msg: str) -> None:
    sys.stderr.write(f"ERROR: {msg}\n")
    sys.exit(1)


def load_config() -> dict:
    if not CONFIG_PATH.exists():
        die(
            f"{CONFIG_PATH} not found. "
            "Copy config.example.yaml to config.yaml and fill in placeholders."
        )

    text = CONFIG_PATH.read_text(encoding="utf-8")

    # strip full-line comments so {{...}} inside comments doesn't trip the check
    scannable = "\n".join(
        line for line in text.splitlines() if not line.lstrip().startswith("#")
    )
    left = PLACEHOLDER_RE.findall(scannable)
    if left:
        die(
            "config.yaml still contains unreplaced placeholders:\n  "
            + "\n  ".join(sorted(set(left)))
        )

    return yaml.safe_load(text)


def read_prompt(name: str) -> str:
    path = PROMPTS_DIR / name
    if not path.exists():
        die(f"missing prompt file: {path}")
    return path.read_text(encoding="utf-8")


def build_nanobot_config(cfg: dict) -> dict:
    providers = cfg["providers"]
    gates = cfg["gates"]

    nanobot_cfg = {
        "providers": {
            "anthropic": {"apiKey": providers["anthropic"]["api_key"]},
            "openai":    {"apiKey": providers["openai"]["api_key"]},
            "google":    {"apiKey": providers["google"]["api_key"]},
        },

        "agents": {
            "defaults": {
                "model": gates["gate1"]["model"],
                "temperature": gates["gate1"].get("temperature", 0.1),
            },
            "named": {
                "ti-gate-1": {
                    "model": gates["gate1"]["model"],
                    "temperature": gates["gate1"].get("temperature", 0.1),
                    "systemPrompt": read_prompt("gate.1.v1.md"),
                },
                "ti-gate-2": {
                    "model": gates["gate2"]["model"],
                    "temperature": gates["gate2"].get("temperature", 0.1),
                    "systemPrompt": read_prompt("gate.2.v1.md"),
                },
            },
        },

        "gate3Consensus": {
            "models": gates["gate3"]["consensus"],
            "quorum": gates["gate3"].get("quorum", 2),
            "systemPrompt": read_prompt("gate.3.v1.md"),
            "temperature": gates["gate3"].get("temperature", 0.1),
        },

        "mcpServers": {
            "ti-audit-tools": {
                "transport": "http",
                "url": "http://mcp-tools:9000/mcp",
            }
        },

        "channels": {"websocket": {"enabled": False}},
        "memory":   {"enabled": False},
        "dream":    {"enabled": False},

        "api": {
            "openaiCompatible": {
                "enabled": True,
                "host": cfg["nanobot"]["host"],
                "port": cfg["nanobot"]["port"],
                "authToken": cfg["nanobot"]["trigger_secret"],
            }
        },
    }
    return nanobot_cfg


def build_env(cfg: dict) -> str:
    providers = cfg["providers"]
    ledger = cfg["ledger"]
    nanobot = cfg["nanobot"]
    wd = cfg.get("watchdog", {}) or {}
    wd_notifiers = wd.get("notifiers", {}) or {}
    wd_thresh = wd.get("thresholds", {}) or {}
    wd_telegram = wd_notifiers.get("telegram", {}) or {}

    lines = [
        "# Auto-generated by scripts/render_nanobot_config.py — do not edit by hand.",
        f"ANTHROPIC_API_KEY={providers['anthropic']['api_key']}",
        f"OPENAI_API_KEY={providers['openai']['api_key']}",
        f"GOOGLE_API_KEY={providers['google']['api_key']}",
        f"LEDGER_REPO={ledger['repo']}",
        f"LEDGER_BRANCH={ledger['branch']}",
        f"LEDGER_GITHUB_TOKEN={ledger['github_token']}",
        f"AUDIT_RECEIVER_PORT={nanobot.get('receiver_port', nanobot['port'])}",
        f"NANOBOT_PORT={nanobot['port']}",
        f"NANOBOT_TRIGGER_SECRET={nanobot['trigger_secret']}",
        "NANOBOT_CHAT_URL=http://nanobot:8080/v1/chat/completions",
        "NANOBOT_GATE1_MODEL=ti-gate-1",
        "AUDIT_SWEEP_ON_STARTUP=true",
        "AUDIT_SWEEP_INTERVAL_SEC=300",
        "AUDIT_SWEEP_LIMIT=10",
        # watchdog
        f"WATCHDOG_ENABLED={'true' if wd.get('enabled', True) else 'false'}",
        f"WATCHDOG_INTERVAL_SEC={int(wd.get('interval_seconds', 300))}",
        f"WD_REJECTED_RATIO_MAX={wd_thresh.get('rejected_ratio_max', 0.85)}",
        f"WD_REJECTED_RATIO_MIN={wd_thresh.get('rejected_ratio_min', 0.05)}",
        f"WD_REJECTED_MIN_SAMPLE={int(wd_thresh.get('rejected_min_sample', 10))}",
        f"WD_PENDING_STUCK_MINUTES={int(wd_thresh.get('pending_stuck_minutes', 15))}",
        f"WATCHDOG_WEBHOOK_URL={wd_notifiers.get('webhook_url', '')}",
        f"WATCHDOG_TELEGRAM_BOT_TOKEN={wd_telegram.get('bot_token', '')}",
        f"WATCHDOG_TELEGRAM_CHAT_ID={wd_telegram.get('chat_id', '')}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    cfg = load_config()

    NANOBOT_OUT.parent.mkdir(parents=True, exist_ok=True)
    NANOBOT_OUT.write_text(
        json.dumps(build_nanobot_config(cfg), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    os.chmod(NANOBOT_OUT, 0o600)

    ENV_OUT.write_text(build_env(cfg), encoding="utf-8")
    os.chmod(ENV_OUT, 0o600)

    print(f"✓ rendered {NANOBOT_OUT.relative_to(ROOT)}")
    print(f"✓ rendered {ENV_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
